export type ProductActionType = 'SET_PRODUCTS'|'SELECTED_PRODUCT'|'REMOVE_SELECTED_PRODUCT';

const SET_PRODUCTS:ProductActionType = 'SET_PRODUCTS';
const SELECTED_PRODUCT:ProductActionType = 'SELECTED_PRODUCT';
const REMOVE_SELECTED_PRODUCT:ProductActionType = 'REMOVE_SELECTED_PRODUCT';

export {
    SET_PRODUCTS,
    SELECTED_PRODUCT,
    REMOVE_SELECTED_PRODUCT
}